version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /package.json
    destination: /var/www/html/
  - source: /scripts/
    destination: /scripts/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
