version: '3.8'

services:
  backend:
    build: ./backend
    image: studivent-backend
    container_name: backend-app
    ports:
      - "3000:3000"
    env_file: backend/.env
    restart: unless-stopped
